[workspace]
resolver = "2"
members = ["aravis", "aravis-sys", "aravis-utils"]

[workspace.dependencies]
gio = "0.20.0"
gio-sys = "0.20.0"
glib = "0.20.0"
glib-sys = "0.20.0"
gobject-sys = "0.20.0"
image = "0.24.6"
